//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Report
{
    public partial class CustomerAnalytics
    {
        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// ddlCustomerType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCustomerType;

        /// <summary>
        /// ddlLimit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlLimit;

        /// <summary>
        /// btnExport control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnExport;

        /// <summary>
        /// litTotalCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalCustomers;

        /// <summary>
        /// litNewCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNewCustomers;

        /// <summary>
        /// litReturningCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litReturningCustomers;

        /// <summary>
        /// litVIPCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litVIPCustomers;

        /// <summary>
        /// litSelectedYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSelectedYear;

        /// <summary>
        /// litRepeatCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRepeatCount;

        /// <summary>
        /// gvRepeatCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvRepeatCustomers;

        /// <summary>
        /// litDisplayCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDisplayCount;

        /// <summary>
        /// litTotalCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalCount;

        /// <summary>
        /// gvAllCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvAllCustomers;

        /// <summary>
        /// hfSegmentationData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSegmentationData;

        /// <summary>
        /// hfTopCustomersData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfTopCustomersData;

        /// <summary>
        /// hfTopCustomersLabels control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfTopCustomersLabels;
    }
}
