// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace Take_Time_BangPhra.Admin.Report
{
    public partial class ProfitLoss
    {
        /// <summary>
        /// ddlPeriodType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlPeriodType;

        /// <summary>
        /// divMonth control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMonth;

        /// <summary>
        /// ddlMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMonth;

        /// <summary>
        /// divYear control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divYear;

        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// divQuarter control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divQuarter;

        /// <summary>
        /// ddlQuarter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlQuarter;

        /// <summary>
        /// btnExport control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnExport;

        /// <summary>
        /// btnRefresh control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRefresh;

        /// <summary>
        /// litTotalRevenue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalRevenue;

        /// <summary>
        /// litRevenueTrend control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRevenueTrend;

        /// <summary>
        /// litTotalCOGS control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalCOGS;

        /// <summary>
        /// litCOGSPercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCOGSPercent;

        /// <summary>
        /// litGrossProfit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litGrossProfit;

        /// <summary>
        /// litGrossMargin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litGrossMargin;

        /// <summary>
        /// litTotalExpenses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalExpenses;

        /// <summary>
        /// litExpensesPercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litExpensesPercent;

        /// <summary>
        /// litNetProfit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNetProfit;

        /// <summary>
        /// litNetMargin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNetMargin;

        /// <summary>
        /// litPeriodDisplay control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPeriodDisplay;

        /// <summary>
        /// litAccomRevenue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAccomRevenue;

        /// <summary>
        /// litAccomRevenuePercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAccomRevenuePercent;

        /// <summary>
        /// litProductRevenue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProductRevenue;

        /// <summary>
        /// litProductRevenuePercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProductRevenuePercent;

        /// <summary>
        /// litServiceRevenue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litServiceRevenue;

        /// <summary>
        /// litServiceRevenuePercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litServiceRevenuePercent;

        /// <summary>
        /// litOtherRevenue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litOtherRevenue;

        /// <summary>
        /// litOtherRevenuePercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litOtherRevenuePercent;

        /// <summary>
        /// litTotalRevenueDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalRevenueDetail;

        /// <summary>
        /// litProductCOGS control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProductCOGS;

        /// <summary>
        /// litProductCOGSPercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProductCOGSPercent;

        /// <summary>
        /// litTotalCOGSDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalCOGSDetail;

        /// <summary>
        /// litTotalCOGSPercentDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalCOGSPercentDetail;

        /// <summary>
        /// litGrossProfitDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litGrossProfitDetail;

        /// <summary>
        /// litGrossProfitPercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litGrossProfitPercent;

        /// <summary>
        /// litSalaryExpense control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSalaryExpense;

        /// <summary>
        /// litSalaryExpensePercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSalaryExpensePercent;

        /// <summary>
        /// litUtilityExpense control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUtilityExpense;

        /// <summary>
        /// litUtilityExpensePercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUtilityExpensePercent;

        /// <summary>
        /// litMaintenanceExpense control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMaintenanceExpense;

        /// <summary>
        /// litMaintenanceExpensePercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMaintenanceExpensePercent;

        /// <summary>
        /// litOtherExpense control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litOtherExpense;

        /// <summary>
        /// litOtherExpensePercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litOtherExpensePercent;

        /// <summary>
        /// litTotalExpensesDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalExpensesDetail;

        /// <summary>
        /// litTotalExpensesPercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalExpensesPercent;

        /// <summary>
        /// litNetProfitDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNetProfitDetail;

        /// <summary>
        /// litNetProfitPercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNetProfitPercent;

        /// <summary>
        /// litGrossMarginMetric control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litGrossMarginMetric;

        /// <summary>
        /// litNetMarginMetric control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNetMarginMetric;

        /// <summary>
        /// litCOGSRatio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCOGSRatio;

        /// <summary>
        /// litOpExRatio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litOpExRatio;

        /// <summary>
        /// hfComparisonLabels control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfComparisonLabels;

        /// <summary>
        /// hfComparisonRevenue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfComparisonRevenue;

        /// <summary>
        /// hfComparisonExpenses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfComparisonExpenses;

        /// <summary>
        /// hfComparisonProfit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfComparisonProfit;
    }
}
