//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Account
{
    public partial class CheckDocument_New
    {
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlMonth;
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnExport;

        protected global::System.Web.UI.WebControls.Label lblCat1Cash;
        protected global::System.Web.UI.WebControls.Label lblCat1KBANK;
        protected global::System.Web.UI.WebControls.Label lblCat1KTB;
        protected global::System.Web.UI.WebControls.Label lblCat1Director;
        protected global::System.Web.UI.WebControls.Label lblCat1Total;

        protected global::System.Web.UI.WebControls.Label lblCat2Cash;
        protected global::System.Web.UI.WebControls.Label lblCat2KBANK;
        protected global::System.Web.UI.WebControls.Label lblCat2KTB;
        protected global::System.Web.UI.WebControls.Label lblCat2Director;
        protected global::System.Web.UI.WebControls.Label lblCat2Total;

        protected global::System.Web.UI.WebControls.Label lblCat3Cash;
        protected global::System.Web.UI.WebControls.Label lblCat3KBANK;
        protected global::System.Web.UI.WebControls.Label lblCat3KTB;
        protected global::System.Web.UI.WebControls.Label lblCat3Director;
        protected global::System.Web.UI.WebControls.Label lblCat3Total;

        protected global::System.Web.UI.WebControls.Label lblCat4Cash;
        protected global::System.Web.UI.WebControls.Label lblCat4KBANK;
        protected global::System.Web.UI.WebControls.Label lblCat4KTB;
        protected global::System.Web.UI.WebControls.Label lblCat4Director;
        protected global::System.Web.UI.WebControls.Label lblCat4Total;

        protected global::System.Web.UI.WebControls.Label lblTotalCash;
        protected global::System.Web.UI.WebControls.Label lblTotalKBANK;
        protected global::System.Web.UI.WebControls.Label lblTotalKTB;
        protected global::System.Web.UI.WebControls.Label lblTotalDirector;
        protected global::System.Web.UI.WebControls.Label lblGrandTotal;

        protected global::System.Web.UI.WebControls.Panel pnlValidation;
        protected global::System.Web.UI.WebControls.Label lblValidationIcon;
        protected global::System.Web.UI.WebControls.Label lblValidationMessage;

        protected global::System.Web.UI.WebControls.Label lblDocCount;
        protected global::System.Web.UI.WebControls.Label lblTotalVAT;
        protected global::System.Web.UI.WebControls.Label lblDateRange;

        protected global::System.Web.UI.WebControls.CheckBox chkEnableDelete;
        protected global::System.Web.UI.WebControls.GridView gvDetails;
    }
}
