//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Account
{
    public partial class CheckDocument
    {
        /// <summary>
        /// pnlAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAlert;

        /// <summary>
        /// lblAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAlert;

        /// <summary>
        /// txtStartDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;

        /// <summary>
        /// txtEndDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;

        /// <summary>
        /// ddlPaymentChannel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlPaymentChannel;

        /// <summary>
        /// ddlRevenueCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRevenueCategory;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// btnToday control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnToday;

        /// <summary>
        /// btnThisMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnThisMonth;

        /// <summary>
        /// btnExport control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnExport;

        /// <summary>
        /// lblCashTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCashTotal;

        /// <summary>
        /// lblTransferTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTransferTotal;

        /// <summary>
        /// lblCreditTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCreditTotal;

        /// <summary>
        /// lblGrandTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblGrandTotal;

        /// <summary>
        /// rptCategoryBreakdown control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCategoryBreakdown;

        /// <summary>
        /// rptPaymentBreakdown control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPaymentBreakdown;

        /// <summary>
        /// lblTransactionCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTransactionCount;

        /// <summary>
        /// gvTransactions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvTransactions;

        /// <summary>
        /// gvDailySummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvDailySummary;
    }
}
