//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin
{
    public partial class Dashboard
    {
        /// <summary>
        /// litUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUsername;

        /// <summary>
        /// litLastUpdate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLastUpdate;

        /// <summary>
        /// litRevenueToday control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRevenueToday;

        /// <summary>
        /// litRevenueTrend control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRevenueTrend;

        /// <summary>
        /// litBookingsToday control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBookingsToday;

        /// <summary>
        /// litCheckIns control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCheckIns;

        /// <summary>
        /// litCheckOuts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCheckOuts;

        /// <summary>
        /// litOccupancyRate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litOccupancyRate;

        /// <summary>
        /// litOccupancyDetails control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litOccupancyDetails;

        /// <summary>
        /// litNetProfit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNetProfit;

        /// <summary>
        /// litProfitMargin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProfitMargin;

        /// <summary>
        /// rptAlerts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAlerts;

        /// <summary>
        /// litNoAlerts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNoAlerts;

        /// <summary>
        /// hfRevenueTrendData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfRevenueTrendData;

        /// <summary>
        /// hfPaymentMethodData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfPaymentMethodData;

        /// <summary>
        /// hfTopAccommodationsData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfTopAccommodationsData;
    }
}
